### ISSUE TITLE
AtCoder Problemsの難易度推定アルゴリズム変更に追従

### ISSUE THREAD

**Issue by trineutron** [iilj/yukicoder-problems#127]
AtCoder Problemsの難易度推定アルゴリズムが変更されました。変更の経緯は以下のissueで見ることができます。

- [難易度推定に用いるアルゴリズムを公式のレーティングと同じものにする](https://github.com/kenkoooo/AtCoderProblems/issues/814)
- [Implemented binary search-based difficulty estimation.](https://github.com/kenkoooo/AtCoderProblems/pull/815)

yukicoder problemsでもこのアルゴリズムを採用することを提案します。新方式のほうがノイズに強いため、yukicoderとの相性も良いと思われます。

**Comment by iilj** [comment]
新しい難易度推定アルゴリズムについて，まだ精確な理解はできていないので，AtC のほうで何をやっているのか見てみます．

変更のベースになる思想は，ロジスティック回帰における判別力パラメータを固定するというものと理解しています．感覚として yukicoder は AtCoder に比べて判別力のばらつきが大きいので，特にアドホック要素の大きい問題に対してどのような挙動を示すのか，注意すべきでしょう．

**Comment by iilj** [comment]
試しに新しい Difficulty 計算アルゴリズムを実装してみました．
しかしながら，低難易度（特に灰色相当）の問題において，直感よりも高めの推定値となってしまいます．

たとえば，[No\.1285 ゴミ捨て \- yukicoder](https://yukicoder.me/problems/no/1285) の例では以下のようになります．

- 従来の推定アルゴリズム: Difficulty = 0（灰）
- 新しい推定アルゴリズム: Difficulty = 944（緑）

この現象の最大の原因は，yukicoder のコンテスト参加者のレート分布が AtCoder と大きく異なっていることであると考えられます．
![image](https://user-images.githubusercontent.com/59337901/101637920-b9082900-3a70-11eb-90a6-7478ef2b4610.png)
上図のように，yukicoder のコンテスト参加者は緑中位〜橙上位が大半を占めており，この範囲外の参加者は少数です．このような分布だと，新しいアルゴリズムでは Difficulty も緑中位〜橙上位に近い値に寄ってしまいます．問題を参加者に見立ててレーティングを按分する状況を想像すれば，何となくそのようになりそうだ，と納得できます．

下図は，横軸＝従来の推定値，縦軸＝新しい推定値，でプロットした散布図です．
（従来の推定値で Difficulty=147 付近に点が直線上に集中しているのは，sklearn のロジスティック回帰を使っているが故の事象だと思われます．）
![image](https://user-images.githubusercontent.com/59337901/101641913-b1974e80-3a75-11eb-992b-119c61f623ec.png)
新しい推定方法では，恐らく水色以上の推定値は実情により即したものになっているのですが，緑以下については直感よりも高く出ているように見受けられます．

低難易度帯の問題については現状の推定値が低めに出ているという指摘もあるので，

- 現状の低めの推定値を受け入れる
- 新しい高めの推定値を受け入れる

このどちらを取るか，ということになります．いい方法があればよいのですが．

**Comment by iilj** [comment]
上の文を書いているときは気付かなかったのですが，水色以上でも AC できていない（あえて解いていない）人が一定数いることも効いていそうです．

**Comment by iilj** [comment]
「あえて問題を解いていない高レート保持者を検出して除去する」ということができれば，まともな数字になりそうな気がしています．

**Comment by iilj** [comment]
Difficulty 推定を二分探索ベースに置き換えました．ざっと見た感じでは問題なさそうですので，これで行こうと思います．
